# Always change these three variables for your situation.
substitutions:
  # the HA entity id of the thermostat to control
  thermostat_id: climate.hallway_thermostat
  # The HA entity id you want for this dial
  dial_name: hallway-dial-1
  # The display name you want for this dial in HA
  dial_friendly_name: Hallway Dial

packages:
  remote_package_shorthand: github://esphome/quasistoic/ha-tools/m5stack_dial/thermostat.yaml@main

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # If you need manual ip configuration. Otherwise comment out the below.
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.0.100
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
